### ISSUE TITLE
mingw32-make dependency

### ISSUE THREAD

**Issue by db4** [conan-community/conan-tbb#2]
I see in the package description that on Windows it "requires mingw32-make to be installed and in system path". But maybe just make "mingw_installer/1.0@conan/stable" its build dependency?

**Comment by memsharded** [comment]
Sure, but that shouldn't be done in the recipe by default.
Build tools like mingw or cmake should be added as build_requires in profiles. This is the only way the end-user can choose to provide their own tools: "ey, why is conan installing a cmake, or a mingw if I already have mine installed in my machine"?

Actually, conan-package-tools can use the mingw_installer as build-require for mingw builds automatically. 

Does this make sense? Thanks!

**Comment by db4** [comment]
Well, we could check in `conanfile.py` if `mingw32-make` is available with [shutil.which()](https://docs.python.org/dev/library/shutil.html#shutil.which) (Python3) or `distutils.spawn.find_executable()` (Python2). If it does not, we can conditionally require `mingw_installer`. My only concern is that `mingw_installer` is huge, so maybe a smaller package `mingw_binutils` or something like that would be more convenient.

**Comment by memsharded** [comment]
Yes, could be done, but that is going down the rabbit hole. It is possible that mingw32-make is not the one to use, but there is some ``make`` somewhere in the system, for example. Finding things in the system is quite complex and almost impossible to do it robustly. And why not checking if VisualStudio is on the system too and act accordingly? Then we need to have packages for at least the mainstream versions of Visual Studio, that could be redistributable. That is not an easy task. And also cmake. We could check if cmake is on the system, and if not use a build_require to conditionally depend on it. And also check for all different versions of gcc and clang compilers, and if they are not installed, use a build-requirement to fetch it.

This should be done in all packages too.

This would lead to overly complex, fragile and difficult to maintain packages. It is reasonable to assume that most developers will have the version of mingw, cmake, or visual studio in the machines they want to use for development, already installed in their machines. If not, build_requires in profiles, can help automating their installation. But it is important to keep package recipes decoupled as much as possible of environment configuration.

**Comment by db4** [comment]
Ok, I generally agree. But then IMHO we need an option to explicitly specify where to get a build tool like `make` (via dependency on some conan package or via an OS path in some settings). I don't like the idea to add full `Mingw` bin folder (or `Msys` or `Cygwin` or whatever) to the default system `Path` because they interfere with native build tools non-obvious way. E.g., `Cygwin` contains `link.exe` that shadows MSVC link, `Mingw` contains python 2.7 that is found when configuring packages while I would like to use native 3.6 etc. Yes, one can play with directory order in system `Path`, but these are unnecessary problems that can be avoided.

**Comment by memsharded** [comment]
Yes, we have been developing recently some utilities to deal with these problems, please have a look to: http://docs.conan.io/en/latest/systems_cross_building/windows_subsystems.html#controlling-the-build-environment

**Comment by db4** [comment]
Thanks a lot, I'll look into that

**Comment by danimtb** [comment]
Hi @db4 

There were som changes in the recipe to target the use of `make` in a more generic way

https://github.com/conan-community/conan-tbb/blob/6063dcb244292463e96f2ded80f1035bb56376e9/conanfile.py#L36#L39

We think this method is general enough to be used in different situations and is working well with ming_installer build require set in a profile.

I will mark this issue as solved but please let us know any other issue you have in our community issue tracker: https://github.com/conan-community/community/issues
