### ISSUE TITLE
Linux build is broken

### ISSUE THREAD

**Issue by db4** [conan-community/conan-tbb#4]
I'm trying to use TBB under Linux as OpenCV dependency and OpenCV build fails with
```
/home/dbely/.conan/data/TBB/4.4.4/conan/stable/package/2de3d908e1d9b246c9b2b6ea5c083ff1297f138b/include/tbb/flow_graph.h:64:28: fatal error: compat/tuple: No such file or directory
compilation terminated.
```
Does anyone know how to fix that?

**Comment by memsharded** [comment]
The TBB in conan-community is supposed to be ok (passes our internal tests), but it is also very new. How are you re-using it? Which changes did you do to OpenCV? Based in the conan-community/conan-opencv repo?

**Comment by db4** [comment]
> The TBB in conan-community is supposed to be ok (passes our internal tests)

Can you try to `#include "tbb/flow_graph.h"` in your test?

>  Which changes did you do to OpenCV? Based in the conan-community/conan-opencv repo?

No, actually it's my own recipe. I will make it public soon and drop a comment here once it's ready.

**Comment by memsharded** [comment]
Worked on Windows, pushing changes to see CI, and will check in linux if fails.

**Comment by memsharded** [comment]
Seems to be working in Linux too, in my machine and in travis: https://travis-ci.org/conan-community/conan-tbb/builds/353944195

Might be something specific for your compiler? ``fatal error: compat/tuple: No such file or directory`` seems like a system/compiler header, which system, compiler, version are you using?

**Comment by db4** [comment]
> Might be something specific for your compiler? fatal error: compat/tuple: No such file or directory seems like a system/compiler header, which system, compiler, version are you using?

I use docker image lasote/conangcc5 (CI), but the same problem exists for my Win10/WSL development machine. Except this error there are also huge amount of warnings that are not present in your Linux CI logs. OK, I will publish my OpenCV recipe and we will continue then.

**Comment by db4** [comment]
OK, I see the problem now. Your test recipe includes `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")` while OpenCV build does not use `-std=c++11` (at least by  default). If you remove `-std=c++11` your test fails just the same way. Why do you force c++11? Looks like TBB itself is built without it, so client code should not require it as well. BTW, if OpenCV downloads & builds TBB itself (when no prebuilt lib is available), it has no such problems. Maybe due to more recent TBB, but still.

**Comment by db4** [comment]
Well, actually everything is quite simple. You don't package C++ header files without extension (like `tbb/compat/tuple`), so they are missing in the package and gcc cannot find them.

**Comment by memsharded** [comment]
Ok, got it! Thanks very much for investigating this, I am going to fix it.

**Comment by memsharded** [comment]
And the travis-ci build for linux is green, please try again: https://travis-ci.org/conan-community/conan-tbb

**Comment by db4** [comment]
Thanks, now Linux build is completed without errors but still huge amount of warnings is generated like these:
```
/home/dbely/.conan/data/TBB/4.4.4/conan/stable/package/2de3d908e1d9b246c9b2b6ea5c083ff1297f138b/include/tbb/task_scheduler_observer.h:25:5: note: in expansion of macro ‘__TBB_ARENA_OBSERVER’
 #if __TBB_ARENA_OBSERVER || __TBB_SLEEP_PERMISSION
     ^
/home/dbely/.conan/data/TBB/4.4.4/conan/stable/package/2de3d908e1d9b246c9b2b6ea5c083ff1297f138b/include/tbb/tbb_config.h:432:38: warning: "__TBB_CPF_BUILD" is not defined [-Wundef]
     #define __TBB_SLEEP_PERMISSION ((__TBB_CPF_BUILD||TBB_PREVIEW_LOCAL_OBSERVER)&& __TBB_SCHEDULER_OBSERVER)
                                      ^
/home/dbely/.conan/data/TBB/4.4.4/conan/stable/package/2de3d908e1d9b246c9b2b6ea5c083ff1297f138b/include/tbb/task_scheduler_observer.h:25:29: note: in expansion of macro ‘__TBB_SLEEP_PERMISSION’
 #if __TBB_ARENA_OBSERVER || __TBB_SLEEP_PERMISSION
                             ^
```
But probably it's OpenCV's configuration problem that cannot/should not be fixed on your side.

**Comment by memsharded** [comment]
Ok, thanks for telling. Yes, I don't see how the packaging will affect or produce those warnings, but it might be that it is necessary to activate some preprocessor directive. In that case, we could try to add it to the ``package_info()`` method.

As it seems the broken linux issue is solved, I think we can close the issue, just re-open if necessary. Cheers.

**Comment by db4** [comment]
> Yes, I don't see how the packaging will affect or produce those warnings

I can now explain how. OpenCV enables a lot of compiler options, including `-Wundef` which would trigger these warnings inside tbb header files if their include dir were specified via `-I<tbb_dir>`. But OpenCV specifies tbb include dir using
```cmake
target_include_directories(tbb SYSTEM PUBLIC $<BUILD_INTERFACE:${tbb_src_dir}/include>
    PRIVATE "${CMAKE_CURRENT_BINARY_DIR}"
)
```
which is translated to `-isystem <tbb_dir>`. Without conan it works but once I inject `conanbuildinfo.cmake ` into OpenCV cmake project, conan's `-I<tbb_dir>` supersedes OpenCV's `-isystem <tbb_dir>` and all warnings are there.

What to do with this? Don't inject `conanbuildinfo.cmake ` or have an option in conan to generate `-isystem` instead of `-I` or patch `CMakeLists.txt` in different places removing `-Wundef`? I don't know.

**Comment by memsharded** [comment]
Yes, I think the includes are not ``-isystem`` by default, because there were more users wanting to see warning from the include headers, because more often that not, those headers are their own packages.

But we will check again, just in case it is possible to do something relatively clean regarding this.

**Comment by memsharded** [comment]
I have just checked. In the global approach (not using targets), the ``-isystem`` can be activated defining the cmake variable ``CONAN_SYSTEM_INCLUDES``

The problem with targets is that it seems necessary to use:

```cmake
set_property(TARGET {name} PROPERTY INTERFACE_INCLUDE_DIRECTORIES 
```
but that syntax doesn't allow specifying SYSTEM. Any hint on this?

**Comment by db4** [comment]
> The problem with targets is that it seems necessary to use:
> ```cmake
> set_property(TARGET {name} PROPERTY INTERFACE_INCLUDE_DIRECTORIES 
> ```
> but that syntax doesn't allow specifying SYSTEM. Any hint on this?

No, one can use
```cmake
target_include_directories({name} SYSTEM INTERFACE
```
as I explained above. As for me, I decided not to inject any conan cmake settings into OpenCV project (it's too intrusive) but just set
```python
        cmake_options["CMAKE_INCLUDE_PATH"] = ";".join(self.deps_cpp_info.include_paths)
        cmake_options["CMAKE_LIBRARY_PATH"] = ";".join(self.deps_cpp_info.lib_paths)
```
Fortunately in my case it's turned to be quite enough. As for general approach, I hope that [non-intrusive integration with CMake](https://github.com/conan-io/conan/issues/2463) will be possible some day.

**Comment by memsharded** [comment]
I see, the reason we had ``set_property`` is because it is used for everything in the targets, like:

```cmake
  set_property(TARGET {name} PROPERTY INTERFACE_LINK_LIBRARIES ${{CONAN_PACKAGE_TARGETS_{uname}}} ${{CONAN_SHARED_LINKER_FLAGS_{uname}_LIST}} ${{CONAN_EXE_LINKER_FLAGS_{uname}_LIST}}
                                                                 $<$<CONFIG:Release>:${{CONAN_PACKAGE_TARGETS_{uname}_RELEASE}} ${{CONAN_SHARED_LINKER_FLAGS_{uname}_RELEASE_LIST}} ${{CONAN_EXE_LINKER_FLAGS_{uname}_RELEASE_LIST}}>
                                                                 $<$<CONFIG:RelWithDebInfo>:${{CONAN_PACKAGE_TARGETS_{uname}_RELEASE}} ${{CONAN_SHARED_LINKER_FLAGS_{uname}_RELEASE_LIST}} ${{CONAN_EXE_LINKER_FLAGS_{uname}_RELEASE_LIST}}>
                                                                 $<$<CONFIG:MinSizeRel>:${{CONAN_PACKAGE_TARGETS_{uname}_RELEASE}} ${{CONAN_SHARED_LINKER_FLAGS_{uname}_RELEASE_LIST}} ${{CONAN_EXE_LINKER_FLAGS_{uname}_RELEASE_LIST}}>
                                                                 $<$<CONFIG:Debug>:${{CONAN_PACKAGE_TARGETS_{uname}_DEBUG}} ${{CONAN_SHARED_LINKER_FLAGS_{uname}_DEBUG_LIST}} ${{CONAN_EXE_LINKER_FLAGS_{uname}_DEBUG_LIST}}>
                                                                 {deps})
    set_property(TARGET {name} PROPERTY INTERFACE_INCLUDE_DIRECTORIES ${{CONAN_INCLUDE_DIRS_{uname}}}
                                                                      $<$<CONFIG:Release>:${{CONAN_INCLUDE_DIRS_{uname}_RELEASE}}>
                                                                      $<$<CONFIG:RelWithDebInfo>:${{CONAN_INCLUDE_DIRS_{uname}_RELEASE}}>
 ```

But yes, maybe we could try  to add it too. I have created an issue here: https://github.com/conan-io/conan/issues/2629
