### ISSUE TITLE
Add bin to PATH

### ISSUE THREAD

**Issue by db4** [conan-community/conan-tbb#6]
To help consumer apps find `tbb.dll` the recipe should add `bin` to the search path:
```
def package_info(self):
    # ...
    self.env_info.PATH.append(os.path.join(self.package_folder, "bin"))
```
BTW, why conan doesn't do that by default like appending `bin` to `self.cpp_info.bindirs`?

**Comment by memsharded** [comment]
The ``virtualrunenv`` (composable with other virtualenvs), already append to PATH the ``bindirs``, no need to specify it explicitly in the recipes, have you tried it?

**Comment by db4** [comment]
Thanks, I missed that. Then please update [the docs](https://docs.conan.io/en/latest/reference/conanfile/methods.html#method-package-infol), that are slightly confusing:

>One of the most typical usages for the PATH environment variable, would be to add the current binary package directories to the path, so consumers can use those executables easily:
```
# assuming the binaries are in the "bin" subfolder
self.env_info.PATH.append(os.path.join(self.package_folder, "bin")
```

**Comment by memsharded** [comment]
Agree, opened https://github.com/conan-io/docs/issues/676

**Comment by db4** [comment]
OK, closing the issue
